import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
              <Image
                src="/logo.svg"
                alt="gelado compressor Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
               <Image
                src="/nodebook-demo.webp"
                alt="gelado compressor Logo"
                className={styles.notebookImage}
                width={745}
                height={535}
                priority
              />
      </main>
      <section>
        dadad
      </section>
      <footer>
        dada
      </footer>
    </>
  )
}
